roles: app,discovery
kubeClusterName: {{cluster_name}}
proxyAddr: {{cluster_name}}.{{domain_name}}:443
teleportClusterName: {{cluster_name}}.{{domain_name}}
joinParams:
  method: kubernetes
  tokenName: kubernetes-token
kubernetesDiscovery:
  - types: ["app"]
    namespaces: ["*"]
    labels:
      noa.re/discover: enabled
