clusterName: {{cluster_name}}.playground.swigger.io
highAvailability:
  requireAntiAffinity: true
  certManager:
    enabled: true
    issuerName: letsencrypt
    issuerKind: ClusterIssuer
persistence:
  storageClassName: gp2

annotations:
  service:
    external-dns.alpha.kubernetes.io/hostname: "*.{{cluster_name}}.playground.swigger.io,{{cluster_name}}.playground.swigger.io"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: HTTP
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /
