# these values are borrowed from https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/
settings:
  clusterName: {{cluster_name}}
  interruptionQueue: {{cluster_name}}

controller:
  env:
    - name: AWS_REGION
      value: {{aws_region}}
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{account_id}}:role/{{cluster_name}}-karpenter