# SPDX-FileCopyrightText: 2026 The clusterspinner contributors
# SPDX-License-Identifier: MIT

clusterName: {{cluster_name}}
hostNetwork: true

enableCertManager: true
serviceAccount:
  create: false
  name: aws-load-balancer-controller