apiVersion: cert-manager.io/v1                                                                                                                                                   
kind: Issuer                                                                                                                                                                     
metadata:
  name: leaf
spec:
  ca:
    secretName: ca-tls
