# SPDX-FileCopyrightText: 2026 The clusterspinner contributors
# SPDX-License-Identifier: MIT

crds:
  install: true
configs:
  params:
    server.insecure: true
server:
  enabled: false
dex:
  enabled: false
notifications:
  enabled: false
