# SPDX-FileCopyrightText: 2026 The clusterspinner contributors
# SPDX-License-Identifier: MIT

ipam:
  mode: eni
eni:
  enabled: true
  awsEnablePrefixDelegation: true
  subnetTags:
    karpenter.sh/discovery: ${cluster_name}
egressMasqueradeInterfaces: eth+
routingMode: native
kubeProxyReplacement: true
k8sServiceHost: ${k8s_service_host}
k8sServicePort: "443"
envoy:
  enabled: false
hubble:
  tls:
    enabled: false
