# SPDX-FileCopyrightText: 2026 The clusterspinner contributors
# SPDX-License-Identifier: MIT

crds:
  install: true
configs:
  params:
    server.insecure: true
server:
  service:
    annotations:
      teleport.dev/port: http
      teleport.dev/name: argo
    labels:
      noa.re/discover: enabled
global:
  domain: argo.{{cluster_name}}.{{domain_name}}
dex:
  enabled: false

