ipam:
  mode: eni
eni:
  enabled: true
  nodeSpec:
    subnetTags:
      - karpenter.sh/discovery={{cluster_name}}
hubble:
  tls:
    auto:
      method: certmanager
      certManagerIssuerRef:
        name: leaf
  relay:
    enabled: true
  ui:
    enabled: true
    service:
      labels:
        noa.re/discover: enabled
      annotations:
        teleport.dev/name: hubble
routingMode: native
kubeProxyReplacement: true
k8sServiceHost: {{k8s_service_host}}
k8sServicePort: "443"
