eni:
  enabled: true
  nodeSpec:
    subnetTags:
      - karpenter.sh/discovery={{cluster_name}}
hubble:
  tls:
    auto:
      method: certmanager
      certManagerIssuerRef:
        name: aws-load-balancer-selfsigned-issuer
        kind: Issuer
        group: cert-manager.io
